# Generated by Django 5.0 on 2024-01-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
