# Generated by Django 5.0 on 2023-12-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variaton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variaton',
            new_name='Variation',
        ),
    ]
